// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjCRS.Models;

namespace ProjCRS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181003235056_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("ProjCRS.Models.CrimeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("State");

                    b.Property<string>("StreetAddress");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("CrimeLocation");
                });

            modelBuilder.Entity("ProjCRS.Models.Criminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("City");

                    b.Property<string>("EducationLevel");

                    b.Property<bool>("Employed");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<int?>("Income");

                    b.Property<string>("LastName");

                    b.Property<string>("State");

                    b.Property<string>("StreetAddress");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Criminal");
                });

            modelBuilder.Entity("ProjCRS.Models.CriminalActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CaseStatus");

                    b.Property<int>("CriminalCodeId");

                    b.Property<int>("CriminalId");

                    b.Property<int>("LocationId");

                    b.Property<DateTime>("TimeOfOccurance");

                    b.HasKey("Id");

                    b.HasIndex("CriminalCodeId");

                    b.HasIndex("CriminalId");

                    b.HasIndex("LocationId");

                    b.ToTable("CriminalActivity");
                });

            modelBuilder.Entity("ProjCRS.Models.CriminalCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("CriminalCode");
                });

            modelBuilder.Entity("ProjCRS.Models.CriminalActivity", b =>
                {
                    b.HasOne("ProjCRS.Models.CriminalCode", "CriminalCode")
                        .WithMany("CriminalActivities")
                        .HasForeignKey("CriminalCodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjCRS.Models.Criminal", "Criminal")
                        .WithMany("CriminalActivities")
                        .HasForeignKey("CriminalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjCRS.Models.CrimeLocation", "Location")
                        .WithMany("CriminalActivities")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
